import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import type { Assignment } from '../../types';
import type { GradeHistoryPoint } from '../../lib/localExperience';
import { readToolkit, updateToolkit } from '../../lib/localExperience';
import { useApp } from '../../store/context';
import { Card, CardHeader } from '../ui/Card';
import { Button } from '../ui/Button';
import { TextInput } from '../ui/Field';
import { workStateOf } from '../../lib/workState';
import { formatScore } from '../../types/grades';

export function ClassWorkspace({ subject, assignments, gradeHistory }: { subject: string; assignments: Assignment[]; gradeHistory: GradeHistoryPoint[] }) {
  const { state, now } = useApp();
  const [toolkit, setToolkit] = useState(readToolkit);
  const [topic, setTopic] = useState('');
  const update = (patch: Parameters<typeof updateToolkit>[0]) => setToolkit(updateToolkit(patch));
  const contact = toolkit.teacherContacts[subject] ?? { name: '', email: '', officeHours: '' };
  const exams = state.exams.filter((exam) => exam.subject.toLowerCase() === subject.toLowerCase());
  const exam = exams[0];
  const topics = exam ? toolkit.examTopics[exam.id] ?? [] : [];
  const comfortable = topics.filter((item) => item.status === 'comfortable').length;
  const recovery = assignments.filter((item) => ['missing', 'overdue'].includes(workStateOf(item, now))).sort((a, b) => a.estimatedMinutes - a.loggedMinutes - (b.estimatedMinutes - b.loggedMinutes));
  const allTotals = useMemo(() => Object.values(state.assignments.filter((item) => item.status !== 'Completed').reduce<Record<string, number>>((out, item) => { out[item.subject] = (out[item.subject] ?? 0) + Math.max(0, item.estimatedMinutes - item.loggedMinutes); return out; }, {})), [state.assignments]);
  const thisLoad = assignments.filter((item) => item.status !== 'Completed').reduce((sum, item) => sum + Math.max(0, item.estimatedMinutes - item.loggedMinutes), 0);
  const averageLoad = allTotals.length ? allTotals.reduce((sum, value) => sum + value, 0) / allTotals.length : 0;
  const ids = new Set(assignments.map((item) => item.id));
  const sessions = state.completedSessions.filter((session) => session.assignmentId && ids.has(session.assignmentId));
  const calibration = sessions.length >= 2 ? sessions.reduce((sum, session) => sum + session.actualMinutes / Math.max(1, session.plannedMinutes), 0) / sessions.length : null;
  const latest = gradeHistory.at(-1);
  const saveContact = (patch: Partial<typeof contact>) => update({ teacherContacts: { ...toolkit.teacherContacts, [subject]: { ...contact, ...patch } } });

  return <section className="grid gap-4 lg:grid-cols-2" aria-label="Class workspace">
    <Card><CardHeader title="Class notebook" subtitle="Notes and useful links stay on this device."/><textarea className="lk-input min-h-40 resize-y" maxLength={3000} value={toolkit.classNotes[subject] ?? ''} placeholder="Study notes, recurring instructions, useful links…" onChange={(event) => update({ classNotes: { ...toolkit.classNotes, [subject]: event.target.value } })}/><p className="mt-2 text-caption lk-muted">Saved locally as you type.</p></Card>
    <Card><CardHeader title="Teacher contact" subtitle="A local card for office hours and contact details."/><div className="space-y-2"><TextInput value={contact.name} placeholder="Teacher name" aria-label="Teacher name" onChange={(event) => saveContact({ name: event.target.value })}/><TextInput type="email" value={contact.email} placeholder="Email" aria-label="Teacher email" onChange={(event) => saveContact({ email: event.target.value })}/><TextInput value={contact.officeHours} placeholder="Office hours or room" aria-label="Office hours or room" onChange={(event) => saveContact({ officeHours: event.target.value })}/></div></Card>
    <Card><CardHeader title="Missing-work recovery" subtitle="Smallest realistic wins first; nothing is silently dropped."/>{recovery.length ? <ol className="space-y-2">{recovery.map((item, index) => <li key={item.id} className="flex items-center gap-3 rounded-xl lk-sunken p-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-brand-100 text-caption font-black text-brand-700 dark:bg-brand-900/50 dark:text-brand-200">{index + 1}</span><span className="min-w-0 flex-1"><span className="block truncate text-body font-bold lk-strong">{item.title}</span><span className="text-caption lk-muted">{Math.max(0,item.estimatedMinutes-item.loggedMinutes)}m remaining</span></span></li>)}</ol> : <p className="text-body lk-muted">No genuinely missing or overdue work in this class.</p>}<div className="mt-3 rounded-xl border lk-border px-3 py-2 text-caption lk-muted">Workload check: <strong className="lk-strong">{thisLoad} minutes open</strong>. {averageLoad > 0 && thisLoad > averageLoad * 1.5 ? 'This is unusually heavy compared with your other classes.' : 'This is within your current class-load range.'}</div></Card>
    <Card><CardHeader title="Exam readiness" subtitle={exam ? `${exam.name} · ${exam.examDate}` : 'Add an exam to start a topic wheel.'}/>{exam ? <><div className="flex items-center gap-4"><div className="lk-readiness-wheel grid h-24 w-24 shrink-0 place-items-center rounded-full" style={{ '--ready': `${topics.length ? (comfortable/topics.length)*100 : 0}%` } as CSSProperties}><div className="grid h-16 w-16 place-items-center rounded-full lk-raised text-center"><span className="text-heading font-extrabold lk-strong">{comfortable}/{topics.length}</span></div></div><div className="min-w-0 flex-1"><div className="flex gap-2"><TextInput value={topic} placeholder="Add a topic" onChange={(event) => setTopic(event.target.value)}/><Button disabled={!topic.trim()} onClick={() => { update({ examTopics: { ...toolkit.examTopics, [exam.id]: [...topics, { id: crypto.randomUUID(), text: topic.trim(), status: 'not_reviewed' as const }].slice(0,40) } }); setTopic(''); }}>Add</Button></div><p className="mt-2 text-caption lk-muted">Tap a topic to move from not reviewed → learning → comfortable.</p></div></div><div className="mt-3 flex flex-wrap gap-2">{topics.map((item) => <button type="button" key={item.id} className={`rounded-full border px-3 py-1.5 text-caption font-bold ${item.status === 'comfortable' ? 'border-mint-500 bg-mint-400/15 text-mint-600 dark:text-mint-400' : item.status === 'learning' ? 'border-brand-500 bg-brand-400/10 text-brand-600 dark:text-brand-300' : 'lk-border lk-muted'}`} onClick={() => { const nextStatus = item.status === 'not_reviewed' ? 'learning' : item.status === 'learning' ? 'comfortable' : 'not_reviewed'; update({ examTopics: { ...toolkit.examTopics, [exam.id]: topics.map((entry) => entry.id === item.id ? { ...entry, status: nextStatus } : entry) } }); }}>{item.text}</button>)}</div><label className="mt-3 block text-caption font-bold lk-strong">Private confidence note<TextInput value={toolkit.examConfidence[exam.id] ?? ''} maxLength={240} placeholder="Before or after the exam: what feels ready, and what does not?" onChange={(event) => update({ examConfidence: { ...toolkit.examConfidence, [exam.id]: event.target.value } })}/></label></> : <p className="text-body lk-muted">No upcoming exam is listed for this class.</p>}</Card>
    <Card><CardHeader title="Estimate calibration" subtitle="Based only on finished local sessions."/><p className="text-display font-extrabold lk-strong">{calibration === null ? '—' : `${Math.round(calibration*100)}%`}</p><p className="text-body lk-muted">{calibration === null ? 'Finish at least two class sessions for a useful comparison.' : calibration > 1.15 ? 'Sessions usually run longer than planned. Consider slightly larger estimates.' : calibration < .85 ? 'Sessions usually finish faster than planned.' : 'Your estimates are landing close to actual time.'}</p></Card>
    <Card><CardHeader title="Grade-change journal" subtitle="Notes attach to real readings; LockIn predicts nothing."/>{latest ? <><p className="text-heading font-extrabold lk-strong">{formatScore(latest.score)} · {new Date(latest.readAt).toLocaleDateString()}</p><textarea className="lk-input mt-3 min-h-24 resize-y" maxLength={300} value={toolkit.gradeNotes[latest.readAt] ?? ''} placeholder="Example: retake posted, project added, category changed…" onChange={(event) => update({ gradeNotes: { ...toolkit.gradeNotes, [latest.readAt]: event.target.value } })}/></> : <p className="text-body lk-muted">No recorded grade reading yet.</p>}</Card>
  </section>;
}
