/* GENERATED by scripts/gen-extension-config.mjs — do not edit by hand.
   Source of truth: lockin.config.json (+ LOCKIN_ENV / LOCKIN_APP_ORIGIN). */
/**
 * Classic-script twin of shared/config.js.
 *
 * content/bridge.js runs as a classic content script and cannot use `import`,
 * so this file is listed ahead of it in manifest.json's content_scripts. Both
 * files share one isolated world, so the assignment below is visible there and
 * nowhere else on the page.
 */
globalThis.__LOCKIN_BUILD__ = {
  BUILD_ENV: "development",
  ALLOWED_APP_ORIGINS: ["http://localhost:5173","http://127.0.0.1:5173"],
  DEFAULT_APP_URL: "http://localhost:5173/home",
};
