/* GENERATED by scripts/gen-extension-config.mjs — do not edit by hand.
   Source of truth: lockin.config.json (+ LOCKIN_ENV / LOCKIN_APP_ORIGIN). */
/**
 * Where the LockIn web app is allowed to live.
 *
 * The content script refuses to relay messages from any origin not in this
 * list, which is what stops a random page from turning Focus Mode off. The
 * service worker checks it a second time on the sender's real origin.
 */
export const BUILD_ENV = "development";

export const ALLOWED_APP_ORIGINS = [
  "http://localhost:5173",
  "http://127.0.0.1:5173"
];

/** Fallback used by the popup / block page for the "Open LockIn" button. */
export const DEFAULT_APP_URL = "http://localhost:5173/home";

export function isAllowedOrigin(origin) {
  return ALLOWED_APP_ORIGINS.includes(origin);
}
